# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 12:04
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations
from django.db.migrations import RunPython


def forwards_func(apps, schema_editor):
    User = get_user_model()
    db_alias = schema_editor.connection.alias
    u = User.objects.using(db_alias).create(
        username='admin',
        email='admin@django.com',
        is_superuser=True,
        is_staff=True,
    )
    u.set_password('admin')
    u.save()


def reverse_func(apps, schema_editor):
    User = get_user_model()
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).get(username='admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        RunPython(forwards_func, reverse_func)
    ]
